version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    user: "1000"    # Use 'id' on the console to get your uid
    networks:
      - backend
    volumes:
      - ${PWD}/code:/app  ## While developing it might be worth

  db:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Svp3rC0mp1xpA4A$goD
      MYSQL_DATABASE: db
    volumes:
      - ${PWD}/database:/var/lib/mysql
    ports:
      - 3306:3306 # nasty
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
